def homepage():
    print('                     Welcome to the Annual Hangman game!')
    print('*----------------------------------------------------------------------------*')
    print('|    100     |       200     |       300     |       400     |       500     |')
    print('*----------------------------------------------------------------------------*')


def hangman(guess):
    if guess == 5:
        print('             |-----------|')
        print('             |           |')
        print('             |           |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('              _ _ _ _ _ _|_ _ _ _ _ _')
    if guess == 4:
        print('             |-----------|')
        print('             |           |')
        print('             |           |')
        print('            _|_          |')
        print('           (X_X)         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('             _ _ _ _ _ _ |_ _ _ _ _ _')
    elif guess == 3:
        print('             |-----------|')
        print('             |           |')
        print('             |           |')
        print('            _|_          |')
        print('           (X_X)         |')
        print('             |           |')
        print('             |           |')
        print('        _ _ _|           |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('             _ _ _ _ _ _ |_ _ _ _ _ _')
    elif guess == 2:
        print('             |-----------|')
        print('             |           |')
        print('             |           |')
        print('            _|_          |')
        print('           (X_X)         |')
        print('             |           |')
        print('             |           |')
        print('        _ _ _| _ _ _     |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('                         |')
        print('             _ _ _ _ _ _ |_ _ _ _ _ _')
    elif guess == 1:
        print('             |-----------|')
        print('             |           |')
        print('             |           |')
        print('            _|_          |')
        print('           (X_X)         |')
        print('             |           |')
        print('             |           |')
        print('        _ _ _| _ _ _     |')
        print('             |           |')
        print('             |           |')
        print('             |           |')
        print('            /            |')
        print('           /             |')
        print('          /              |')
        print('                         |')
        print('             _ _ _ _ _ _ |_ _ _ _ _ _')
    elif guess == 0:
        print('             |-----------|')
        print('             |           |')
        print('             |           |')
        print('            _|_          |')
        print('           (X_X)         |')
        print('             |           |')
        print('             |           |')
        print('        _ _ _| _ _ _     |')
        print('             |           |')
        print('             |           |')
        print('             |           |')
        print('            / \          |')
        print('           /   \         |')
        print('          /     \        |')
        print('                         |')
        print('             _ _ _ _ _ _ |_ _ _ _ _ _')
